language: python

python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y p7zip-full

install:
  - pip install -r requirements.txt

script:
  - python pysymsrv.py
  - python generateindex.py

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  verbose: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
